Repository amrtgaber/aoe2-random-civ-draft, pull requests merged in 2022-09, with the labels that each got.

#4 Minor refactors. Move separator to app. Some styling.
  src/App.tsx
  src/components/civ-draft-parameters/civ-draft-parameters.scss
  src/components/civ-draft-parameters/index.tsx
  src/components/civ-draft-result-container/index.tsx
  src/components/civ-draft/index.tsx
  src/components/footer/footer.scss
  src/components/footer/footer.test.tsx
  src/components/footer/index.tsx
  src/components/separator/index.tsx
  src/components/separator/separator.scss
  src/components/staging-civ-pool/index.tsx
Labels: refactor

#5 Tech tree filter refactors v2
  .eslintrc.js
  src/api/tech-tree-item-api.ts
  src/components/civ-draft-parameters/civ-draft-parameters.scss
  src/components/civ-draft-parameters/index.tsx
  src/components/civ-draft-result-container/draft-civ-button/index.tsx
  src/components/civ-draft-result-container/index.tsx
  src/components/civ-draft/index.tsx
  src/components/civ/index.tsx
  src/components/footer/index.tsx
  src/components/save-civ-pool/index.tsx
  src/components/staging-civ-pool/index.tsx
  src/components/tech-tree-filter/index.tsx
  src/components/tech-tree-item/index.tsx
  src/components/tech-tree-item/tech-tree-item.scss
  src/components/top-app-bar/index.tsx
  src/store/civs-slice/civs-slice.spec.ts
  src/store/civs-slice/index.ts
  src/store/draft-parameters-slice/draft-parameters-slice.spec.ts
  src/store/draft-parameters-slice/index.ts
  src/store/shared-store-utils.ts
  src/test/filled-test-state.ts
Labels: refactor

#8 Tech tree filter consolidation refactor
  src/components/tech-tree-filter-options/index.tsx
  src/components/tech-tree-filter-search/index.tsx
  src/components/tech-tree-filter-tags/filters.ts
  src/components/tech-tree-filter-tags/index.tsx
  src/components/tech-tree-filter-tags/tech-tree-filter-tags.scss
  src/components/tech-tree-filter/index.tsx
  src/components/tech-tree-filter/tech-tree-filter.scss
  src/components/tech-tree-item/index.tsx
  src/store/tech-tree-filter-slice/filter-civ-pool.ts
  src/store/tech-tree-filter-slice/index.ts
  src/store/tech-tree-filter-slice/tech-tree-filter-service/index.ts
  src/store/tech-tree-filter-slice/tech-tree-filter-service/search-service.ts
  src/store/tech-tree-filter-slice/tech-tree-filter-service/sort-service.ts
  src/store/tech-tree-filter-slice/tech-tree-filter-service/tags-service/index.ts
  src/store/tech-tree-filter-slice/tech-tree-filter-service/tags-service/tags.ts
  src/test/filled-test-state.ts
Labels: refactor

#10 make tests run without failing
  src/api/buildings/buildings-api.test.ts
  src/api/tech-tree-item-api.ts
  src/api/techs/techs-api.test.ts
  src/api/units/units-api.test.ts
  src/store/ages-slice/ages-slice.spec.ts
  src/store/buildings-slice/buildings-slice.spec.ts
  src/store/civs-slice/civs-slice.spec.ts
  src/store/techs-slice/techs-slice.spec.ts
  src/store/units-slice/units-slice.spec.ts
Labels: bug, testing

#9 update visuals
  package-lock.json
  package.json
  public/assets/images/tech-tree/age-icons/castle_age.png
  public/assets/images/tech-tree/age-icons/dark_age.png
  public/assets/images/tech-tree/age-icons/feudal_age.png
  public/assets/images/tech-tree/age-icons/imperial_age.png
  public/index.html
  src/App.tsx
  src/api/buildings/buildings-api.test.ts
  src/api/tech-tree-item-api.ts
  src/api/techs/techs-api.test.ts
  src/api/units/units-api.test.ts
  src/components/civ-draft-parameters/civ-draft-parameters.scss
  src/components/civ-draft-result-container/draft-civ-button/draft-civ-button.scss
  src/components/civ-draft/civ-draft.scss
  src/components/civ-draft/index.tsx
  src/components/civ/civ-animations.scss
  src/components/civ/civ.scss
  src/components/loading/index.tsx
  src/components/loading/loading.scss
  src/components/separator/index.tsx
  src/components/separator/separator.scss
  src/components/staging-civ-pool/index.tsx
  src/components/staging-civ-pool/staging-civ-pool.scss
  src/components/tech-tree-filter-options/index.tsx
  src/components/tech-tree-filter-options/tech-tree-filter-options.scss
  src/components/tech-tree-filter-search/tech-tree-filter-search.scss
  src/components/tech-tree-filter-tags/index.tsx
  src/components/tech-tree-filter-tags/tech-tree-filter-tags.scss
  src/components/tech-tree-filter/tech-tree-filter.scss
  src/components/tech-tree-item/index.tsx
  src/components/tech-tree-item/tech-tree-item-animations.scss
  src/components/tech-tree-item/tech-tree-item.scss
  src/components/top-app-bar/top-app-bar.scss
  src/shared-styles/lib/animation.scss
  src/shared-styles/lib/box-shadow.scss
  src/shared-styles/lib/button.scss
  src/shared-styles/lib/color.scss
  src/shared-styles/lib/grid-item-name.scss
  src/shared-styles/lib/index.scss
  src/store/ages-slice/ages-slice.spec.ts
  src/store/buildings-slice/buildings-slice.spec.ts
  src/store/civs-slice/civs-slice.spec.ts
  src/store/tech-tree-filter-slice/index.ts
  src/store/tech-tree-filter-slice/tech-tree-filter-slice.spec.ts
  src/store/techs-slice/techs-slice.spec.ts
  src/store/units-slice/units-slice.spec.ts
Labels: enhancement

#16 Electron
  .gitignore
  package-lock.json
  package.json
  src/electron.js
  src/preload.js
Labels: enhancement

#17 shuffle sort to test sorting properly for ages api
  src/api/ages/ages-api.spec.ts
Labels: bug
